const items = [
  {
    id: 1,
    title: 'Buttermilk Pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/pancakes.jpeg', 
    desc: `Ніжні млинці на маслянці з карамелізованими бананами та сиропом. Ідеальний вибір для ситного сніданку.`,
  },
  {
    id: 2,
    title: 'Diner Double Burger',
    category: 'lunch',
    price: 13.99,
    img: './images/double-burger.jpeg', 
    desc: `Подвійний бургер з соковитими котлетами, свіжими овочами та сиром чеддер. Смажена картопля входить у комплект.`,
  },
  {
    id: 3,
    title: 'Godzilla Milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/godzilla-milkshake.jpeg', 
    desc: `Великий молочний коктейль з шоколадом, вершками та посипкою з вафельних крихт. Вибух смаку!`,
  },
  {
    id: 4,
    title: 'Egg & Sausage Breakfast',
    category: 'breakfast',
    price: 12.99,
    img: './images/egg-sausage-breakfast.jpeg', 
    desc: `Смажені яйця з соковитою ковбаскою та хрустким тостом. Ідеально для енергійного початку дня.`,
  },
  {
    id: 5,
    title: 'Classic Caesar Salad',
    category: 'lunch',
    price: 10.99,
    img: './images/caesar-salad.jpeg', 
    desc: `Традиційний салат Цезар з куркою, листям романо, пармезаном та хрусткими крутонами.`,
  },
  {
    id: 6,
    title: 'Oreo Dream Shake',
    category: 'shakes',
    price: 7.99,
    img: './images/oreo-shake.jpeg', 
    desc: `Шоколадний молочний коктейль з шматочками Oreo та вершковою пінкою. Солодкий сон наяву!`,
  },
  {
    id: 7,
    title: 'Bacon Cheeseburger',
    category: 'lunch',
    price: 14.99,
    img: './images/bacon-cheeseburger.jpeg', 
    desc: `Соковитий бургер з беконом та розплавленим сиром, подається з маринованими огірками та соусом BBQ.`,
  },
  {
    id: 8,
    title: 'Quinoa Salad',
    category: 'lunch',
    price: 11.99,
    img: './images/quinoa-salad.jpeg', 
    desc: `Легкий і корисний салат з кіноа, авокадо, огірками та зеленою цибулею, заправлений лимонним соком.`,
  },
  {
    id: 9,
    title: 'Strawberry Milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/strawberry-milkshake.jpeg', 
    desc: `Молочний коктейль зі свіжими полуницями, збитими вершками та полуничним сиропом. Ідеальний для спекотних днів.`,
  },
];

export default items;
